//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A6_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sale_ID { get; set; }
        public int Emp_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Sale_Quarter { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
